# Generated by Django 4.1.2 on 2022-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fuel_condition',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='run',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
