# Generated by Django 4.1.2 on 2022-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0002_info_fuel_condition_info_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='car_number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='coordinates',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='fuel_condition',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='run',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='speed',
            field=models.IntegerField(max_length=5),
        ),
    ]
