# Generated by Django 4.1.2 on 2022-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0003_alter_info_car_number_alter_info_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='car_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='coordinates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='fuel_condition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
